// Generated by scripts/process-images.mjs — do not edit by hand.
// Run `npm run media` after changing anything in assets/source.

export type MediaRecord = {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
};

export const media = {
  "akshay-s-house/balcony": {
    src: "/media/akshay-s-house/balcony.webp",
    width: 844,
    height: 475,
    blurDataURL:
      "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACwAQCdASoQAAkAA4BaJagCdAC5G9qAAPz99sBTPlQMyK6dKM0jw/t/uLCXuQs3bEMtkgQTl4GYNZc9OAgLBLHr3NhPn0QDEaL+Azh+/EUEOkO9OJJvbvcukg78G/4A",
  },
  "akshay-s-house/bedroom": {
    src: "/media/akshay-s-house/bedroom.webp",
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAABQAgCdASoQAAwAA4BaJZgCdAYulTDUaN/WqgAA/rYTf3iC+wO2rsbAFRKjubC0o2Sx8b9iSNnuqQLb5XJSyY/etv39YibsH99n5whLuBLeKzKjIgxEl2YIMyzWyr18vfSUh06t6MK+J1iff0/AAA==",
  },
  "akshay-s-house/bedroom-2": {
    src: "/media/akshay-s-house/bedroom-2.webp",
    width: 1671,
    height: 941,
    blurDataURL:
      "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAwAgCdASoQAAkAA4BaJYgCdAEWfkG4jkCQAAD+1fddkvD9ZkLh4qib2wvOmrvPCn3Rlb/V1BRNA/x39i51naz/lOUWJpreFDmxo47/0hwl6q2qDwAAAA==",
  },
  "akshay-s-house/bedroom-png": {
    src: "/media/akshay-s-house/bedroom-png.webp",
    width: 1672,
    height: 941,
    blurDataURL:
      "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAQCdASoQAAkAA4BaJZACdADi1Uu4QAD+1wAlEOtkhff1Q2tlQFAzrMB0jdVox+ISEkyYNIW/cwA+uFllweZWGJenACMvm/y2SoTwRRFZHvctFYEqyY08AAA=",
  },
  "akshay-s-house/bedroom-study": {
    src: "/media/akshay-s-house/bedroom-study.webp",
    width: 1681,
    height: 936,
    blurDataURL:
      "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAwAgCdASoQAAkAA4BaJaACdAEQ0s5u7Y/IAAD+68WZnRV7wYeqI2OYU/cm8VFsQa7BJJ47m/Y2o6DPkIaHPWB6ugGVoo9gmvrQWZTtmA5JMiZ7JwaBSKYm3ByQQASKVQAAAA==",
  },
  "akshay-s-house/dining": {
    src: "/media/akshay-s-house/dining.webp",
    width: 1672,
    height: 941,
    blurDataURL:
      "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAkAA4BaJaACdAD2B4WJO2AA/DxeCw/nKuczCoMDxh6RMcB+RqbDZF+2MJviFnZL2LoWx30l0FZeZ127TCKWvNMzcs1caZoGrLot8rAAAA==",
  },
  "akshay-s-house/kitchen": {
    src: "/media/akshay-s-house/kitchen.webp",
    width: 1672,
    height: 941,
    blurDataURL:
      "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoQAAkAA4BaJYgCdAYq/lKCLecgAP3f/LjBK7CDHhmjyY7WyI24GgsGPCRNhDFM7okgXlReDphJePXrZvkBdR5MsED0NP0CZOYYbYYlasxcJ2bKKK5gAA==",
  },
  "akshay-s-house/living": {
    src: "/media/akshay-s-house/living.webp",
    width: 1684,
    height: 934,
    blurDataURL:
      "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADQAQCdASoQAAkAA4BaJZgCdAD7C6z5wADiWVujLDrAIWmLgOGF9LaGVL4e/+W/kIIPZwjF3BY5C0EhHu4O3xQhlnbgHJ9727FlntI78x9VHU3jc/FAy1pa8wdwAA==",
  },
  "akshay-s-house/living-1": {
    src: "/media/akshay-s-house/living-1.webp",
    width: 1683,
    height: 934,
    blurDataURL:
      "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoQAAkAA4BaJbACdAYsZLq4s+2AAP1Qn9CQDRS+VmnZ5jvcX4Cw/vu3q3KfXyTFwYwUN3y6bh9GA4YHhQ7lnDi5Fg8b874QR9l9suRmh4ulAf/0sgAAAA==",
  },
  "akshay-s-house/living-2": {
    src: "/media/akshay-s-house/living-2.webp",
    width: 1683,
    height: 935,
    blurDataURL:
      "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAkAA4BaJZgCdAEVhINnf4AA+Q/lSG2BQbJyKen1UjDlVBaqeEiorTzFvffpMOge1ODd6Lo5wjnY/OtH35sJwl9cXNHoeiGdq2RZT8pAAA==",
  },
  "akshay-s-house/lounge": {
    src: "/media/akshay-s-house/lounge.webp",
    width: 1677,
    height: 938,
    blurDataURL:
      "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAQAgCdASoQAAkAA4BaJYgCdAEfZAFCn5BQAP7t6CO/J1d4/jmw23zokQb34QVxTioo6IujGaDe/5M/NF32GDEStQmNBBgAAAA=",
  },
  "akshay-s-house/lounge-1": {
    src: "/media/akshay-s-house/lounge-1.webp",
    width: 1678,
    height: 937,
    blurDataURL:
      "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAwAgCdASoQAAkAA4BaJbACdAYtpvHQPuiQAADJR0lOCckPMcisM/vt7SFaU/667tuN3CrjhAsHpHBaILq1fsXO7Lf2ximZnosuWc35zWtncKOnvo2oAAAA",
  },
  "igatpuri/aerial-view": {
    src: "/media/igatpuri/aerial-view.webp",
    width: 2560,
    height: 1429,
    blurDataURL:
      "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoQAAkAA4BaJQBYdiHTAv0AAAD+Zt2V5I78obY3GPeDWqU92SWRy5F9lZDKuTmp1XJNXJOFS2xs2n7ioU9AAA==",
  },
  "igatpuri/master-plan-igt-23-04-26-4-17-page": {
    src: "/media/igatpuri/master-plan-igt-23-04-26-4-17-page.webp",
    width: 1551,
    height: 2560,
    blurDataURL:
      "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAABQBACdASoQABoAPu1iqU2ppaOiMAgBMB2JYgC/OB6u3vT66lKkKNag2+rAAP7v4u5/oeLJOBUgjGIKa6c1I0bUtk/0IBlv6u93QNW3FGTHv45ZiQyC29hpCruiuH2YzuCCFqZzLm+247N6FaajW2ex2Sd97UV+3VGC1/xkqrYBHL2dH0XGVaDAAAA=",
  },
  "mantra-residency/before-renovation-street-view": {
    src: "/media/mantra-residency/before-renovation-street-view.webp",
    width: 539,
    height: 718,
    blurDataURL:
      "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYwCdMoACAIoZLLkqtV/H2ogAAP7rJzYSbBA6KlymeEpLxeEbsMQgY/eWUdfqbZ1oebdeazcXHhUs8HY9gOXkFzCYJean6+RnwXKevvHSPiU9/z9IhJsBTiTNKnsxZ7SLJFtm6E2DriZJWg8Gh5AAAAA=",
  },
  "mantra-residency/elevation": {
    src: "/media/mantra-residency/elevation.webp",
    width: 1280,
    height: 662,
    blurDataURL:
      "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAgAA4BaJYgCdAENnIGUw+AA/tYjbAPaMtrEEIgVK28VAjsHiK8nZxooKOAvfrYIFm2k0uBU8umVYRnV3uPkQOs7L+8AHV4J+DWg0cAAAA==",
  },
  "mantra-residency/elevation-1": {
    src: "/media/mantra-residency/elevation-1.webp",
    width: 720,
    height: 482,
    blurDataURL:
      "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAwAgCdASoQAAsAA4BaJYgCdAERH9UD1H/jAAD++JOFPgV86RquBUPPu6xEXSh1Uowj1fCM8kZ9eHjOEu2VejeVBhEjxGs481jd0Sr75WgAAA==",
  },
  "mantra-residency/facade-night-wide": {
    src: "/media/mantra-residency/facade-night-wide.webp",
    width: 1076,
    height: 717,
    blurDataURL:
      "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAsAA4BaJQBOgCIGu2iNm7wA/vGpMsj+ptEU+T8BwknFdW0JtNppoTLwAhfojT8dp0azxAu6EsDYLttFwTYATTHxPulMAtHQAA==",
  },
  "mantra-residency/fine-dine": {
    src: "/media/mantra-residency/fine-dine.webp",
    width: 1086,
    height: 1280,
    blurDataURL:
      "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAABwBACdASoQABMAPu1iqU2ppaQiMAgBMB2JZgCdMoK8AA5G8kB3/rZOouyAoAD+2YvgMNAj2z7Yh2016mNz4PrwmIHjr8yp1sAXzx3ovD5iiLwNkRTCxGJ58tIfKupcurNfJQiQ2n755B4k58SX/4QG6I9fCkcdMql45ZNgAAA=",
  },
  "mantra-residency/img-9569": {
    src: "/media/mantra-residency/img-9569.webp",
    width: 2560,
    height: 1920,
    blurDataURL:
      "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAwAA4BaJYgCdAD6HPoy2OgAAP7GBjcXauz3TEEkC3Mm8gR2cZPjGCiqOaOTNwxbnUVx3KSh5bLt6Nr2CEmATnJhKkcLKrCGdTlHTwAAAA==",
  },
  "mantra-residency/img-9580": {
    src: "/media/mantra-residency/img-9580.webp",
    width: 2560,
    height: 1920,
    blurDataURL:
      "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAQCdASoQAAwAA4BaJZACsADwhHsQMCAA99kar51ICuj/bMpJdtHNBwksjxh5jPymiPk13DZy78JrloJIOnLSomAIt7Ky0YC1nNiSa0OGtrcOSjfobv9q3AAAAA==",
  },
  "mantra-residency/img-9586": {
    src: "/media/mantra-residency/img-9586.webp",
    width: 1914,
    height: 1436,
    blurDataURL:
      "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAwAA4BaJZACdACyWNKkAADNdGSLpIutefiUOMpxru6zKGIIQp1wOBi0V2siRZcuDLSFetd7sSF/a3UCuKfDu3KBDwpiEwjwAA==",
  },
  "mantra-residency/img-9589": {
    src: "/media/mantra-residency/img-9589.webp",
    width: 2560,
    height: 1920,
    blurDataURL:
      "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwAgCdASoQAAwAA4BaJYgCdAD6HXQ8+PiugAD+g3Tw0jiGPbE/nsfRNil7QWlO/l+MLD15WBOcIdf6zPSmQcM13bHjIM91wFUUQmOlsvsaKHSJZ1pP5vDTUAA=",
  },
  "mantra-residency/img-9591": {
    src: "/media/mantra-residency/img-9591.webp",
    width: 1920,
    height: 2560,
    blurDataURL:
      "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZACdMoGv/gK0LoDL1F0o1AD7q7v6i3BhjqTNFDM1Jp4u0lOkSV7gcaKOTNs+dpoaXZA4mZLWUDDFKLUtvX+BD5MS3tA+Sf0yWPvg1e1mBOrDvwfJyMNdujCaoGetwFfEvb+KPaRaRIqLslpzAljT2ZWDnVrDmcG2BhFrwAA=",
  },
  "mantra-residency/img-9595": {
    src: "/media/mantra-residency/img-9595.webp",
    width: 2138,
    height: 2138,
    blurDataURL:
      "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADQAQCdASoQABAAA4BaJZgCdADHysAuAAD+v717aAt+kclcbcvoVYJs8em/kjEKI3kM59IJZexzmCSF1StIi382hwm238nLF2OCFdG3V+KHIi0k0HMHmwJpLodxflNulX8AAA==",
  },
  "mr-srinivasan-madhavan-residence/bay-window": {
    src: "/media/mr-srinivasan-madhavan-residence/bay-window.webp",
    width: 1681,
    height: 936,
    blurDataURL:
      "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAkAA4BaJZgCdAD2MZcq94AA/sjxPvKdi4t6No8eavqaiMAN1bOlQcatQM5M2/YoyWF6arZBVPY4/GE0lt0GW2x3KqQAAAA=",
  },
  "mr-srinivasan-madhavan-residence/dining": {
    src: "/media/mr-srinivasan-madhavan-residence/dining.webp",
    width: 1672,
    height: 941,
    blurDataURL:
      "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAkAA4BaJZACdADGZFHOgAD5Wv3CpRyqUPbkOSNxKChqQf3y8QKyNvk7O39BaVk3XDnpVEFz6llAl2ctpBXpsYbyrW8QAAA=",
  },
  "mr-srinivasan-madhavan-residence/in-progress/whatsapp-image-2026-08-11-at-12-09-27-pm-1": {
    src: "/media/mr-srinivasan-madhavan-residence/in-progress/whatsapp-image-2026-08-11-at-12-09-27-pm-1.webp",
    width: 960,
    height: 1280,
    blurDataURL:
      "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQBACdASoQABUAPu1iqU2ppaQiMAgBMB2JYwDCgCFopW4vB+jTYu8zUAD6g/4fJBeaw1lERNRwv0PYHpkk9/ysOLSwdSyeivn7PHDpKbsE8aonEOwptOhpxGrv+wAA",
  },
  "mr-srinivasan-madhavan-residence/living": {
    src: "/media/mr-srinivasan-madhavan-residence/living.webp",
    width: 1681,
    height: 936,
    blurDataURL:
      "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwAgCdASoQAAkAA4BaJQBOgUyUcS+WCB6oUAD+qhUeY/0eHIoVqDgj+xOJptu1kVtKGZuoRi7/u2oCUcypJrLJi272IdkgzLG/ip4qWpAj4nF/ZoANIcJddj2uAAAA",
  },
  "mr-srinivasan-madhavan-residence/tv-unit": {
    src: "/media/mr-srinivasan-madhavan-residence/tv-unit.webp",
    width: 1672,
    height: 941,
    blurDataURL:
      "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAwAgCdASoQAAkAA4BaJQBOgCL3XFnHE6BPAADOPo9/+bq3G3OAd1DsIc1fkiGcrB6ESitRCnaatVvW5SbSArM6fnMvDWjB8KVshQ0MVFqOywAA",
  },
  "mr-srinivasan-madhavan-residence/whatsapp-image-2026-08-11-at-12-07-44-pm": {
    src: "/media/mr-srinivasan-madhavan-residence/whatsapp-image-2026-08-11-at-12-07-44-pm.webp",
    width: 576,
    height: 1280,
    blurDataURL:
      "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAABQBACdASoQACQAPu1iq04ppaQiKqwBMB2JYwC3uBZcKdqU/U7ysduKRWTEAP7enG/Faf1H5rfxtJdB53+DqOAVJBu4WtkDnH5JNwb+QGuto59ZEczz5vDHPXTaIWvVsaZAGXEPKxjGE6FAHZU9m6Z9uI2voayaU23y+WdBvt9wht+c02NFZTEPIhp9h3uWWCS3Em8x8bTChAAA",
  },
  "prakash-kori/compound": {
    src: "/media/prakash-kori/compound.webp",
    width: 1402,
    height: 1122,
    blurDataURL:
      "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQAgCdASoQAA0AA4BaJZACdAYtpNwlFOAAAPyyXjx37Sb4uBGuYU+usKL5xC25sRSjMILSu8vL2Q/WzaHKlEkk8Vh1v7abyGKQe981v1aNIisLTH6qfosU50Kmo/SZtAtmYCtQnyWLsAFegAA=",
  },
  "prakash-kori/elevation": {
    src: "/media/prakash-kori/elevation.webp",
    width: 1681,
    height: 936,
    blurDataURL:
      "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAkAA4BaJYgCdH8AGNe2hKxAAP7XL913p2ZQbyOg/T7W0kSg0NnTblHJ0cKRbqLIwlt1MQ15zyuhAZwRik4ekEZNNr3viLv95wbOgAA=",
  },
  "prakash-kori/in-progerss/whatsapp-image-2026-08-04-at-9-10-04-am": {
    src: "/media/prakash-kori/in-progerss/whatsapp-image-2026-08-04-at-9-10-04-am.webp",
    width: 1600,
    height: 900,
    blurDataURL:
      "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoQAAkAA4BaJYgCdAEOSs8oAADN/a5CICpyI/3JkJKQ1As4H1yaaqN+mFslpQ5n6XvjEbLcjveO28/8rnSG6tsXAAA=",
  },
  "residential-extension-and-interior-design/exterior-entrance": {
    src: "/media/residential-extension-and-interior-design/exterior-entrance.jpg",
    width: 549,
    height: 731,
    blurDataURL:
      "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JaACdLwDrAENmA7HHYl7zh6AA+uvmYUVd9qXzAu/Z2jOpHV7Uc85k5kU5HhpX1p/JcudA23apzOVuHULxO4447OTMXZIkocc6dinfqqOKrmRLHghDxuWx1w4wypfIbBuyvB7BlxHut0HYkVsLYAAA",
  },
  "residential-extension-and-interior-design/whatsapp-image-2026-08-11-at-12-11-54-pm-1": {
    src: "/media/residential-extension-and-interior-design/whatsapp-image-2026-08-11-at-12-11-54-pm-1.webp",
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoQAAwAA4BaJZACdADSQw0GzPaAAP7IcKlOgFEyaqiMc1EOUOHzjccUU4xsMXLJ0SPqCLCZi1C7ixLfDituAOq2YQ6HjpkrzBp0oaZh4m9A4AAA",
  },
  "residential-extension-and-interior-design/whatsapp-image-2026-08-11-at-12-11-54-pm-2": {
    src: "/media/residential-extension-and-interior-design/whatsapp-image-2026-08-11-at-12-11-54-pm-2.webp",
    width: 960,
    height: 1280,
    blurDataURL:
      "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAADwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JaACdMoACWTUPDme1j3OAAP3Bqa8KG1bSjA8PpBKD41qyN0o8dQOXhUUDumiOXRU5rmFHtKj0hY1dBRyVsVoEyomt8BKRRql6pVgHZsknSd+plRf3Wcqcj+OWQ70lCINGHHXJwJ7Ll5Oq7SvQcqwAhgCAAkK534ybkAAA",
  },
  "residential-extension-and-interior-design/whatsapp-image-2026-08-11-at-12-11-54-pm-3": {
    src: "/media/residential-extension-and-interior-design/whatsapp-image-2026-08-11-at-12-11-54-pm-3.webp",
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQAgCdASoQAAwAA4BaJZACdADxADFt/fEYAMtMzcCJyqy7A6UTvpDs2wfeWHeqEVLr6VDQLPhYtV/AaLMIi4DKLzScutjvzDcH2oJOhsMarNB+ljl83gVbo1ZiC8T4MCwAAA==",
  },
  "residential-extension-and-interior-design/whatsapp-image-2026-08-11-at-12-17-08-pm": {
    src: "/media/residential-extension-and-interior-design/whatsapp-image-2026-08-11-at-12-17-08-pm.webp",
    width: 691,
    height: 921,
    blurDataURL:
      "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAACwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JaACdOUDIAATb/Te+Rv7eeempq2CIAP7NFHAb8NlgF5JtFA0t6+CTM6fOBJTj3GsQCfyCVxcbAZrEHrXP4qXo/+m8Szz+Cc4KE5k8cLCo9FKJV5kF33GNRGY3wfzf2NG3xegy3jI44pGfyx7PH9hwFiD7lYEzyeDIlZh/MSJwBKLyMDW3BlhpSixI/Mo8tJ8rG/xTe7g4I4nMYAAAAA==",
  },
  "residential-extension-and-interior-design/whatsapp-image-2026-08-11-at-12-17-08-pm-1": {
    src: "/media/residential-extension-and-interior-design/whatsapp-image-2026-08-11-at-12-17-08-pm-1.webp",
    width: 1024,
    height: 576,
    blurDataURL:
      "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAkAA4BaJZACdADp9NMB6CmAAP6tvOjaCwm0MFRPZ6cWV8rYr8Tm7sSFO7OEFRq3w4CFngyfs/CcsxzSUi2ePCsICI3rnB+qyuixAAA=",
  },
  "residential-extension-and-interior-design/whatsapp-image-2026-08-11-at-12-18-18-pm": {
    src: "/media/residential-extension-and-interior-design/whatsapp-image-2026-08-11-at-12-18-18-pm.jpg",
    width: 959,
    height: 1280,
    blurDataURL:
      "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAAAQBACdASoQABYAPu1iqU2ppaOiMAgBMB2JQBOgA3XEjIidQdtMb5BlQAD+ymtcrFyaeWJkGV0LBOQPtAq9n0AEthHMjvUSj3on16q9jJIlaPI7th9LYdGheEs0bMIKYKiaLNJxgqy2e2mPbAh5OlKJ187ZRQY2O1B1TyL4ja/UKJ2bRHuBGmcioQUma4UkDUMSgAAA",
  },
  "rotsons-sales-lounge/1": {
    src: "/media/rotsons-sales-lounge/1.webp",
    width: 1672,
    height: 941,
    blurDataURL:
      "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoQAAkAA4BaJZgCdADs8/X3gADNnSk052uW4h3gWr4u/IA5B02GpIsFGfWRuMlaUFX4nM0UipWK09sdN3VD1r+h2Lb+dU27wK13eiFEgMAAAA==",
  },
  "rotsons-sales-lounge/2": {
    src: "/media/rotsons-sales-lounge/2.webp",
    width: 1672,
    height: 941,
    blurDataURL:
      "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwAgCdASoQAAkAA4BaJZACdH8AF/slXykbAAD+0h/nHhzoUDN01Fi8sVxfo85wCNjQHUJUNnRTHOLNM9UkdVsL3ozHr+Zj1FtgwMTaEqf+NlTLcedysW2QkMZ+iAAA",
  },
  "rotsons-sales-lounge/3": {
    src: "/media/rotsons-sales-lounge/3.webp",
    width: 1678,
    height: 937,
    blurDataURL:
      "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoQAAkAA4BaJZACdAD6JCVrjWEAAP54J89Sum+HtSiv4zho5UkLmnu2WmrH6rb44qjPkxahD0xRl5zx8rhqiezxbj90nt4rKXcFKzmnTSWdYCZD3wAAAA==",
  },
  "rotsons-sales-lounge/4": {
    src: "/media/rotsons-sales-lounge/4.webp",
    width: 1696,
    height: 927,
    blurDataURL:
      "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoQAAkAA4BaJYwCdAEXXIjMygAA/mpb3E2VSnviUTas6pHd+QPnByoK2OafYqn1R92DRQURjATr+Eqd/iA9DaudAAA=",
  },
  "rotsons-sales-lounge/5": {
    src: "/media/rotsons-sales-lounge/5.webp",
    width: 1672,
    height: 941,
    blurDataURL:
      "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoQAAkAA4BaJYwCdAEQdC4eIk8AAP4IeThbWNt5HrAT8ErCqoOBG5DNL51zDvPyQ4Gl/fxx/3vlKtZQyvBE5VsBFMLLIYAA",
  },
  "rotsons-sales-lounge/6": {
    src: "/media/rotsons-sales-lounge/6.webp",
    width: 1683,
    height: 934,
    blurDataURL:
      "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQAgCdASoQAAkAA4BaJbACdEf/geakbXuvaAAA/uyGQtCr9OWiUjHo+fQqzXlCrnzGOoRO0VUwXNf65Z1A+nNIerPA+f49gjD/XjsFzVZpQnQTaNXigEUtWd2AAA==",
  },
  "rotsons-sales-lounge/7": {
    src: "/media/rotsons-sales-lounge/7.webp",
    width: 1410,
    height: 1115,
    blurDataURL:
      "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAwAgCdASoQAA0AA4BaJbACdAEN8DcqqmCDxAD+8wPhuUMZWIm/clmhTcH8GWo679oaXxaG/oHx8JzkJNXiNHYXx75iRgNHlGBbrB46ChBi/NS4mN59CyvY368M4dHiYVxL1pfegAA=",
  },
  "sanctum-square/sanjana-s-hallad-portrait": {
    src: "/media/sanctum-square/sanjana-s-hallad-portrait.webp",
    width: 409,
    height: 409,
    blurDataURL:
      "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoQABAAA4BaJQBOgB6RPL5KgAD+5uUBDnvEMIol6OGKkm4PzH033D7Ct7f8+UL6P3DGHU5wY5V1kxST7ELlTmHyliHcc7hc4F/ftgAA",
  },
  "sanctum-square/whatsapp-image-2026-08-11-at-12-12-17-pm": {
    src: "/media/sanctum-square/whatsapp-image-2026-08-11-at-12-12-17-pm.webp",
    width: 1280,
    height: 959,
    blurDataURL:
      "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAwAA4BaJYgCdAEezBz427EAAP6qCMAm47LuKpJkBV3ssxVrzFl5HOe/EKhFCwwyihcY4gkCyl5NXOJ8OdUgPCiS49c2ReLHvhvMgAA=",
  },
  "sanctum-square/whatsapp-image-2026-08-11-at-12-12-34-pm": {
    src: "/media/sanctum-square/whatsapp-image-2026-08-11-at-12-12-34-pm.webp",
    width: 960,
    height: 1280,
    blurDataURL:
      "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAABwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZgCsFQAAVXeLJFskcNYdHsMKAADJBGyAfTnTjuD8HyLrSFfVwnDAuZRfhA4phMSSIVBMp69F5O/JEG/MSk2E3/6Oaq24ap9qki+CBK4+/UBdt1SqcD+boiouzNMQ1/ye+Jn6GzrWPk7PJ2oT7fQmDAt9mv1TWLSxX8zPIAA=",
  },
  "sanctum-square/whatsapp-image-2026-08-11-at-12-12-45-pm": {
    src: "/media/sanctum-square/whatsapp-image-2026-08-11-at-12-12-45-pm.webp",
    width: 959,
    height: 1280,
    blurDataURL:
      "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAAAwBACdASoQABYAPu1iqU2ppaQiMAgBMB2JagCsABcUytwqL5ajwzSLpQAA+KHDo8JJ1po0cNXgRnMV+wmyXajMzcB5OdxkUuw6lniNLuJVkqffq+1LRx3a50mWTVXKw0R1LY2pu/2jnOLcvdiNGCFuQb3wrzCGXIB1J5w/7g/ovJEVrWrqeLay3Z8Wd73zqXZk3nKyBXx/aGQAAAA=",
  },
  "sanctum-square/whatsapp-image-2026-08-11-at-12-13-00-pm": {
    src: "/media/sanctum-square/whatsapp-image-2026-08-11-at-12-13-00-pm.webp",
    width: 966,
    height: 1280,
    blurDataURL:
      "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JagCdMoACxFfCv6CXhSeeaIAA/tCSKqhvNKmHBW6DwUcZ3gvmsZo3irt9dSPRa2RzAFvDlYOtRBf8z9a1UzwbrcCza8XBFWRmy2snw0fbBNtGYjfW8WSwDOStKYogAAA=",
  },
  "sanctum-square/whatsapp-image-2026-08-11-at-12-13-28-pm": {
    src: "/media/sanctum-square/whatsapp-image-2026-08-11-at-12-13-28-pm.webp",
    width: 960,
    height: 1280,
    blurDataURL:
      "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAADQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQBOgAt6Jw3T6+kRbDiAA/hRwXcesE/Ki9vQlfLfShzFGPPV/rE4GdPXZyeWQbVt4OYYBuzBG8nDRvThvY5Bq7Wvw7ODAc5KD0zq9H911oNTAw1z8rdbkhkBXKufziKpNaIAA",
  },
  "sanctum-square/whatsapp-image-2026-08-11-at-12-13-47-pm": {
    src: "/media/sanctum-square/whatsapp-image-2026-08-11-at-12-13-47-pm.webp",
    width: 960,
    height: 1280,
    blurDataURL:
      "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYgCdMoADR9fyL1/py6bTArAwAP5W8PlwbHX1eKf0TyZnP8P5KOCWCW+NyHUoTnc7IcTUoLITiJ8Aa5glVtXHmiSI2/ruTzHbHTI5i1LGA3HtoiRi3G99GLDke4rIEtnVAwamdnVkxYH8KVSWMNAA",
  },
  "sanctum-square/workspace": {
    src: "/media/sanctum-square/workspace.webp",
    width: 480,
    height: 640,
    blurDataURL:
      "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAADQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JYgCdABWj+bsMOPPgqgAA/rrkYh3cibLlsdGcI+UNGeUufTnLio1S3HgMO88dSgRcxGx4akIERAPuygo0F6rUdB3WXbMxu02pSCyF3qSBoE5ru81uBPwZ5SFe6XIB1CPaz0AA",
  },
  "triumph-salon/1": {
    src: "/media/triumph-salon/1.webp",
    width: 1025,
    height: 684,
    blurDataURL:
      "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQAgCdASoQAAsAA4BaJbACdAYv1R2yWzHgAP7ShXHwdW/Z79Dub6PyZFJKPG7APHwGwlF/hbLFqqKViR0oz7FULBAVQIch8ynzDY7g/eheqoNtpVS26QPUj/8V/L5vdd1KNAvGEpLZiuoAAAA=",
  },
  "triumph-salon/2": {
    src: "/media/triumph-salon/2.webp",
    width: 864,
    height: 579,
    blurDataURL:
      "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAQAgCdASoQAAsAA4BaJbACdLoAAe+7+ycAAP7U8I9VnOX+WXfIVYbZox6d2uv8mTodiboHj1qRpFCG/M1gZT3vby+UC66/zuh9CTE1dFOhmzAHwRSpUa3E35/G9Hcy++TU8ikifAAAAA==",
  },
  "triumph-salon/3": {
    src: "/media/triumph-salon/3.webp",
    width: 925,
    height: 619,
    blurDataURL:
      "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADwAQCdASoQAAsAA4BaJbACdADdJ6TJA2AA/ubF176yNguShJsMHr1rpgNPPlKIzy/B85UlmLTbbtyFZleuJareZHV33I2rPM2es7+VJWTPdLxcv3e/X2R85gUrHPd8PY8b/CF5pSpiAAAA",
  },
  "triumph-salon/4": {
    src: "/media/triumph-salon/4.webp",
    width: 1024,
    height: 682,
    blurDataURL:
      "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQAgCdASoQAAsAA4BaJZACdADp9Ao/DxrAAPaqHHSI93MKei3Y73WqHRjJ5Dsw26eNA4Tn12BcUh2WkrvoMZx5AlF/nkg/TSzSjed67GVf0nEFJkbKASQAAAA=",
  },
  "triumph-salon/5": {
    src: "/media/triumph-salon/5.webp",
    width: 1025,
    height: 684,
    blurDataURL:
      "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQAgCdASoQAAsAA4BaJbACdADydLVqlVYAAP5XsQ/shihalnZ3TnfcSIWoS7HqDICA0L6rObvE3kjAnpHje8ehPodPqzIVArxcSdmWUmLsn166pFf21zt8atqUS9EAAAA=",
  },
  "triumph-salon/styling-stations-hires": {
    src: "/media/triumph-salon/styling-stations-hires.webp",
    width: 1229,
    height: 820,
    blurDataURL:
      "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoQAAsAA4BaJaACdAEfZdM+ZOSAAPaqHHSI9zf0Bube4qe6hoJfcw26eEfwq90Wgv1xXsxGpkcuibz1FWl/nkUsmzSkDQcYpzpl+Wc38icsGu9KUQAAAA==",
  },
  "umarani/1": {
    src: "/media/umarani/1.webp",
    width: 1121,
    height: 941,
    blurDataURL:
      "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAA0AA4BaJYgCdADG2NOj0AAA+VYU9WX7KU8Gd2IjqNVzi8sTT8ludjzez1RbTyC9mC1nPFtxT0vdyPxLV7LWvALelwRXYwmkX0m+hYAAAA==",
  },
  "umarani/2": {
    src: "/media/umarani/2.webp",
    width: 551,
    height: 494,
    blurDataURL:
      "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAACwAQCdASoQAA4AA4BaJQBOgBjMDNvMAP6bk1z4C9S+XY1aK4rAmt9S5RrsR2kLLcX5V4ahirZs2+LiP3UbskhyCM8irSDrUTXfNaOaOcOyx6zPPogAAA==",
  },
  "umarani/chatgpt-image-aug-11-2026-03-56-45-pm": {
    src: "/media/umarani/chatgpt-image-aug-11-2026-03-56-45-pm.webp",
    width: 1395,
    height: 1127,
    blurDataURL:
      "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQAA0AA4BaJQBOgB5yxo2LHAAA/ettPKgnA6UAxDlgdzZp5D6palkD6Oek10Y9Z68do4sO0qmvLuAeWJT/hwLwWjgP4tPRhMaPV+w8AAA=",
  },
  "umarani/chatgpt-image-aug-11-2026-03-59-32-pm": {
    src: "/media/umarani/chatgpt-image-aug-11-2026-03-59-32-pm.webp",
    width: 542,
    height: 443,
    blurDataURL:
      "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoQAA0AA4BaJZACdADDmrfQ2qAA/rZTwZsZ0SRSo9JSdfX+M5/xprBpPFRA6DpvQ5FnGDWTPrNc0Ezdhki2OG/QAAA=",
  },
  "umarani/chatgpt-image-aug-11-2026-12-53-28-pm": {
    src: "/media/umarani/chatgpt-image-aug-11-2026-12-53-28-pm.webp",
    width: 1681,
    height: 936,
    blurDataURL:
      "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkAA4BaJQBOgCPqjBnbAIAA/Pj6q+Xbm5icXP2wjVsFA13qLn0RATWKKxVUbW+oaPA73vtCEWEHSXMec2WHDAAAAA==",
  },
  "umarani/in-progress/living": {
    src: "/media/umarani/in-progress/living.webp",
    width: 524,
    height: 528,
    blurDataURL:
      "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAQCdASoQABAAA4BaJZQAAiAlIYkQAP38gfdxkSCHb3xcgbiU3wet6TYaEV6q5qcfDTJ2AIqKyhJwCmf7lDQAAAA=",
  },
  "umarani/in-progress/screenshot-2026-08-11-161735": {
    src: "/media/umarani/in-progress/screenshot-2026-08-11-161735.webp",
    width: 521,
    height: 603,
    blurDataURL:
      "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADQAwCdASoQABMAPu1iqU2ppaOiMAgBMB2JZwDCgBdWYsSwo9blvAAA+0ID3izBKjOOWo9rCQEev46NU3O/F+qXbBi1jIdbeMQvUsc/v+XeEwI434DVDHKsCj0AAA==",
  },
  "umarani/whatsapp-image-2026-08-11-at-12-07-06-pm": {
    src: "/media/umarani/whatsapp-image-2026-08-11-at-12-07-06-pm.webp",
    width: 1024,
    height: 682,
    blurDataURL:
      "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAsAA4BaJbACdAEM1my3pAAA+g7Rzsx+aAZYVD6g92g4I2yRimsAw+bJQrCyMsTVfR6b5TK/eo/da+i63V8u1CNTnV70u1MgqomrLUcYz+AA",
  },
  "umarani/whatsapp-image-2026-08-11-at-12-07-06-pm-1": {
    src: "/media/umarani/whatsapp-image-2026-08-11-at-12-07-06-pm-1.webp",
    width: 1024,
    height: 682,
    blurDataURL:
      "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAQCdASoQAAsAA4BaJQBOgB6RY6PC+sAA/oUT4duka32yUXXTfF7Us70rQZiPXYkz/GJyb1PJqizEw02JNJ2fnbHoUXEyfdtfea3Sf0cXCvOYArBNPqD6oAAAAA==",
  },
  "umarani/whatsapp-image-2026-08-11-at-12-07-07-pm": {
    src: "/media/umarani/whatsapp-image-2026-08-11-at-12-07-07-pm.webp",
    width: 1024,
    height: 682,
    blurDataURL:
      "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAwAgCdASoQAAsAA4BaJYwCdAEfbg3I+vJ6AAD+bG1si3cCto3cMwz9DTTolfdm/TxcNKe+RqwfV0oaY9HkEW+jgdcdVfrpQGz7e1DRnZO8QAAA",
  },
  "umarani/whatsapp-image-2026-08-11-at-12-07-07-pm-1": {
    src: "/media/umarani/whatsapp-image-2026-08-11-at-12-07-07-pm-1.webp",
    width: 1024,
    height: 682,
    blurDataURL:
      "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAwAgCdASoQAAsAA4BaJagCdAEDpM6my2rHYAD2vOFyBQFaOvPd6UHYC2aKO2lj/Ko1rO0hpWNvJQ5NL/Xt0JkRE3biThO/mC24XGE21kCz7s16P14aAAAA",
  },
} as const satisfies Record<string, MediaRecord>;

// Video in assets/source, deliberately not copied into public/media. To use
// one, copy it in and reference it explicitly — see scripts/process-images.mjs.
//   mantra-residency/img-9594  (assets/source/MANTRA RESIDENCY/IMG_9594.mov)
//   mantra-residency/img-9604  (assets/source/MANTRA RESIDENCY/IMG_9604.MOV)
//   mantra-residency/img-9606  (assets/source/MANTRA RESIDENCY/IMG_9606.MOV)
//   mantra-residency/whatsapp-video-2026-08-11-at-11-43-16-am  (assets/source/MANTRA RESIDENCY/WhatsApp Video 2026-08-11 at 11.43.16 AM.mp4)
//   mantra-residency/whatsapp-video-2026-09-15-at-11-46-37-am  (assets/source/MANTRA RESIDENCY/WhatsApp Video 2026-09-15 at 11.46.37 AM.mp4)
//   mantra-residency/whatsapp-video-2026-09-15-at-11-46-40-am  (assets/source/MANTRA RESIDENCY/WhatsApp Video 2026-09-15 at 11.46.40 AM.mp4)
//   mantra-residency/whatsapp-video-2026-09-15-at-11-46-54-am  (assets/source/MANTRA RESIDENCY/WhatsApp Video 2026-09-15 at 11.46.54 AM.mp4)
//   prakash-kori/in-progerss/whatsapp-video-2026-08-11-at-11-59-12-am-2  (assets/source/PRAKASH KORI/In progerss /WhatsApp Video 2026-08-11 at 11.59.12 AM (2).mp4)
//   umarani/in-progress/dinning  (assets/source/UMARANI/IN PROGRESS/DINNING.mp4)

export type MediaKey = keyof typeof media;
